# Generated by Django 3.2.15 on 2022-10-18 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='表示順')),
                ('active', models.BooleanField(default=True, verbose_name='有効フラグ')),
            ],
            options={
                'verbose_name': '週報内容区分',
                'verbose_name_plural': '週報内容区分',
                'db_table': 'content_type',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='報告日')),
                ('content', models.TextField(blank=True, null=True, verbose_name='報告')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='記入⽇')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_type_weekly_reports', to='wr.contenttype', verbose_name='内容区分')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_user_weekly_reports', to=settings.AUTH_USER_MODEL, verbose_name='記入者')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_weekly_reports', to='user.teammember', verbose_name='報告者')),
            ],
            options={
                'verbose_name': '週報',
                'verbose_name_plural': '週報',
                'db_table': 'weekly_report',
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.UniqueConstraint(fields=('member', 'report_date', 'content_type', 'created_user'), name='report_unique'),
        ),
    ]
