# Generated by Django 3.2.15 on 2022-10-18 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wr', '0001_initial'),
    ]

    from django.db import migrations

    class Migration(migrations.Migration):
        dependencies = [
            ('wr', '0001_initial'),
        ]

        sql = """
               CREATE VIEW report_index_list AS
        SELECT ROW_NUMBER() OVER () AS id,
               report_date,
               tm.id AS team_member_id,
               t.id AS team_id,
               u.id AS user_id,
               min_weekly_report_id
          FROM (
                   SELECT member_id,
                          report_date,
                          min(id) AS min_weekly_report_id
                     FROM weekly_report
                    GROUP BY member_id,
                             report_date
               )
               wr
               INNER JOIN
               team_member tm ON wr.member_id = tm.id
               INNER JOIN
               user u ON tm.user_id = u.id
               INNER JOIN
               team t ON tm.team_id = t.id
         ORDER BY report_date,
                  t.id,
                  u.id;
           """

        reverse_sql = """
               DROP VIEW IF EXISTS report_index_list;
           """

        operations = [
            migrations.RunSQL(sql, reverse_sql),
        ]
