# Generated by Django 3.2.15 on 2022-10-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wr', '0002_auto_20221018_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIndexList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(editable=False, verbose_name='報告日')),
                ('min_weekly_report_id', models.IntegerField(editable=False, verbose_name='週報Id')),
            ],
            options={
                'verbose_name': '週報インデックス',
                'verbose_name_plural': '週報インデックス',
                'db_table': 'report_index_list',
                'managed': False,
            },
        ),
    ]
