# Generated by Django 3.2.15 on 2022-10-19 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wr', '0003_reportindexlist'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weeklyreport',
            name='report_unique',
        ),
        migrations.RemoveField(
            model_name='weeklyreport',
            name='content_type',
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_weekly_reports', to='wr.contenttype', verbose_name='内容区分'),
        ),
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.UniqueConstraint(fields=('member', 'report_date', 'type', 'created_user'), name='report_unique'),
        ),
    ]
