# Generated by Django 3.2.15 on 2022-10-18 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='期限⽇')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('is_done', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='登録ユーザー')),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODO',
                'db_table': 'todo',
            },
        ),
    ]
