# Generated by Django 3.2.15 on 2022-10-18 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Eメールアドレス')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー群',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('blanch', models.CharField(blank=True, max_length=255, null=True, verbose_name='所属名')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='開始⽇')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了⽇')),
            ],
            options={
                'verbose_name': 'チーム',
                'verbose_name_plural': 'チーム群',
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_report', models.BooleanField(default=True, verbose_name='報告可能フラグ')),
                ('can_reply', models.IntegerField(default=0, verbose_name='返信可能フラグ')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='開始⽇')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了⽇')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.team', verbose_name='チーム')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_teams', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'チームメンバー',
                'verbose_name_plural': 'チームメンバー群',
                'db_table': 'team_member',
            },
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('user', 'end_date'), name='member_unique'),
        ),
    ]
